server:
  port: 8888


dubbo:
  application:
    name: demo-provider
  base-package: com.test.dubbo.provider  # dubbo服务发布者所在的包
  registry:
    address: 127.0.0.1                   # zookeeper注册中心的地址
    port: 2182                           # zookeeper注册中心的端口
  protocol:
    name: dubbo
    serialization: hessian2
  provider:
    retries: 0